### ISSUE TITLE
Finalize hook problem

### ISSUE THREAD

**Issue by ionutbalutoiu** [cloudbase/windows-curtin-hooks#1]
On MAAS 2.0, the default commission image used is Xenial, which comes only with Python 3. The quickest and easiest fix for the finalize hook is to change the shebang to point to `python3`.

**Comment by gabriel-samfira** [comment]
fixed by: 

https://github.com/cloudbase/windows-curtin-hooks/commit/9c3649baa6cbef5ffe529f31bc7d8c766e96a113
